# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'camp-quality-nurseApp-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for camp-quality-nurseApp-iOS
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  target 'camp-quality-nurseApp-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
